// packages/solid/src/hooks/useFloating.ts
// credits to Alexis Munsayac
// "https://github.com/lxsmnsyc/solid-floating-ui/tree/main/packages/solid-floating-ui",
import {ReferenceElement} from '@floating-ui/dom';
import {isElement} from '@floating-ui/utils/dom';
import {access} from '@solid-primitives/utils';
import {
  createEffect,
  createMemo,
  createSignal,
  createUniqueId,
  mergeProps,
} from 'solid-js';
import {createMutable} from 'solid-js/store';

import {
  useFloatingTree,
  useUnsafeFloatingTree,
} from '../components/FloatingTree';
import {
  ContextData,
  FloatingContext,
  NarrowedElement,
  ReferenceType,
  UseFloatingOptions,
  UseFloatingReturn,
} from '../types';
import {createPubSub} from '../utils/createPubSub';
import {usePosition} from './usePosition';

export function useFloating<R extends ReferenceElement>(
  options?: UseFloatingOptions<R>,
): UseFloatingReturn<R> {
  const floatingId = createUniqueId();
  const [_domReference, setDomReference] =
    createSignal<NarrowedElement<R> | null>(null);

  const domReference = createMemo(
    () =>
      (options?.elements?.reference?.() || _domReference) as NarrowedElement<R>,
  );
  let domReferenceRef: NarrowedElement<R> | null = null;

  const events = createPubSub();
  const position = usePosition(mergeProps({transform: true}, options));

  const dataRef = createMutable<ContextData>({
    openEvent: undefined,
    ...position,
  });

  const onOpenChange = (open: boolean, event?: Event) => {
    if (open) {
      dataRef.openEvent = event;
    }
    options?.onOpenChange?.(open, event);
  };

  const setPositionReference = (node: ReferenceType | null) => {
    const positionReference = isElement(node)
      ? {
          getBoundingClientRect: () => node.getBoundingClientRect(),
          contextElement: node,
        }
      : node;
    position.refs.setReference(positionReference as R | null);
  };

  const setReference = (node: R | null) => {
    if (isElement(node) || node === null) {
      domReferenceRef = node as NarrowedElement<R> | null;
      //@ts-ignore
      setDomReference(node as NarrowedElement<R> | null);
    }

    // Backwards-compatibility for passing a virtual element to `reference`
    // after it has set the DOM reference.
    if (
      isElement(position.refs.reference()) ||
      position.refs.reference() === null ||
      // Don't allow setting virtual elements using the old technique back to
      // `null` to support `positionReference` + an unstable `reference`
      // callback ref.
      (node !== null && !isElement(node))
    ) {
      position.refs.setReference(node);
    }
  };

  const context = createMemo(() => {
    return mergeProps(
      {
        dataRef, //: mergeProps(dataRef, position),
        nodeId: options?.nodeId,
        floatingId,
        events,
        open: () => access(options?.open) ?? false,
        onOpenChange,
      },
      position,
      {
        refs: mergeProps(
          {
            domReference: domReference(),
          },
          position.refs,
        ),
        elements: mergeProps({domReference}, position.elements),
      },
    );
  });

  //Add the context to the PortalNodes
  const tree = useUnsafeFloatingTree<R>();
  createEffect(() => {
    if (!tree?.()) return;
    const node = tree?.()?.nodesRef?.find(
      (node) => node.id === options?.nodeId,
    );
    if (node) {
      node.context = context() as FloatingContext<R>;
    }
  });

  return {
    get x() {
      return position.x;
    },
    get y() {
      return position.y;
    },
    get isPositioned() {
      return position.isPositioned;
    },
    get placement() {
      return position.placement;
    },
    get strategy() {
      return position.strategy;
    },
    get middlewareData() {
      return position.middlewareData;
    },
    get floatingStyles() {
      return position.floatingStyles;
    },
    get elements() {
      return {
        reference: position.elements.reference,
        floating: position.elements.floating,
        domReference,
      };
    },
    get refs() {
      return mergeProps(position.refs, {
        setReference,
        setPositionReference,
        domReference: domReferenceRef,
      });
    },
    get context() {
      return context;
    },
    get update() {
      return position.update;
    },
  };
}

// packages/react/src/useFloating.ts
import {useFloating as usePosition} from '@floating-ui/react-dom';
import * as React from 'react';
import useLayoutEffect from 'use-isomorphic-layout-effect';

import {useFloatingTree} from './components/FloatingTree';
import {useId} from './hooks/useId';
import {useEvent} from './hooks/utils/useEvent';
import type {
  ContextData,
  FloatingContext,
  NarrowedElement,
  ReferenceType,
  UseFloatingOptions,
  UseFloatingReturn,
} from './types';
import {createPubSub} from './utils/createPubSub';
import {isElement} from './utils/is';

/**
 * Provides data to position a floating element and context to add interactions.
 * @see https://floating-ui.com/docs/react
 */
export function useFloating<RT extends ReferenceType = ReferenceType>(
  options: Partial<UseFloatingOptions> = {}
): UseFloatingReturn<RT> {
  const {open = false, onOpenChange: unstable_onOpenChange, nodeId} = options;

  const [_domReference, setDomReference] =
    React.useState<NarrowedElement<RT> | null>(null);

  const domReference = (options.elements?.reference ||
    _domReference) as NarrowedElement<RT>;

  const position = usePosition<RT>(options);
  const tree = useFloatingTree<RT>();
  const onOpenChange = useEvent(unstable_onOpenChange);

  const domReferenceRef = React.useRef<NarrowedElement<RT> | null>(null);
  const dataRef = React.useRef<ContextData>({});
  const events = React.useState(() => createPubSub())[0];

  const floatingId = useId();

  const setPositionReference = React.useCallback(
    (node: ReferenceType | null) => {
      const positionReference = isElement(node)
        ? {
            getBoundingClientRect: () => node.getBoundingClientRect(),
            contextElement: node,
          }
        : node;
      position.refs.setReference(positionReference as RT | null);
    },
    [position.refs]
  );

  const setReference = React.useCallback(
    (node: RT | null) => {
      if (isElement(node) || node === null) {
        (domReferenceRef as React.MutableRefObject<Element | null>).current =
          node;
        setDomReference(node as NarrowedElement<RT> | null);
      }

      // Backwards-compatibility for passing a virtual element to `reference`
      // after it has set the DOM reference.
      if (
        isElement(position.refs.reference.current) ||
        position.refs.reference.current === null ||
        // Don't allow setting virtual elements using the old technique back to
        // `null` to support `positionReference` + an unstable `reference`
        // callback ref.
        (node !== null && !isElement(node))
      ) {
        position.refs.setReference(node);
      }
    },
    [position.refs]
  );

  const refs = React.useMemo(
    () => ({
      ...position.refs,
      setReference,
      setPositionReference,
      domReference: domReferenceRef,
    }),
    [position.refs, setReference, setPositionReference]
  );

  const elements = React.useMemo(
    () => ({
      ...position.elements,
      domReference: domReference,
    }),
    [position.elements, domReference]
  );

  const context = React.useMemo<FloatingContext<RT>>(
    () => ({
      ...position,
      refs,
      elements,
      dataRef,
      nodeId,
      floatingId,
      events,
      open,
      onOpenChange,
    }),
    [position, nodeId, floatingId, events, open, onOpenChange, refs, elements]
  );

  useLayoutEffect(() => {
    const node = tree?.nodesRef.current.find((node) => node.id === nodeId);
    if (node) {
      node.context = context;
    }
  });

  return React.useMemo(
    () => ({
      ...position,
      context,
      refs,
      elements,
    }),
    [position, refs, elements, context]
  ) as UseFloatingReturn<RT>;
}
