// packages/solid/src/components/Composite.tsx
import {MaybeAccessor} from '@solid-primitives/utils';
import {
  Accessor,
  createMemo,
  createSignal,
  JSX,
  mergeProps,
  ParentComponent,
  Setter,
  Show,
  splitProps,
  untrack,
} from 'solid-js';

import {
  ARROW_DOWN,
  ARROW_LEFT,
  ARROW_RIGHT,
  ARROW_UP,
  findNonDisabledIndex,
  getGridNavigatedIndex,
  getMaxIndex,
  getMinIndex,
  isIndexOutOfBounds,
} from '../utils/composite';
import {destructure} from '../utils/destructure';
import {enqueueFocus} from '../utils/enqueueFocus';
import {
  createFloatingListContext,
  FloatingList,
  useListItem,
} from './FloatingList';

type CompositeContextProps = {
  activeIndex: Accessor<number>;
  onNavigate(index: number): void;
};

type RenderProp =
  | (() => JSX.Element)
  | ((
      props: Accessor<Omit<JSX.HTMLAttributes<HTMLElement>, 'ref'>>,
    ) => JSX.Element);

interface CompositeProps {
  render?: RenderProp;
  orientation?: MaybeAccessor<'horizontal' | 'vertical' | 'both'>;
  loop?: MaybeAccessor<boolean>;
  cols?: MaybeAccessor<number>;
  disabledIndices?: MaybeAccessor<number[]>;
  activeIndex?: Accessor<number>;
  onNavigate?: Setter<number>;
}

const horizontalKeys = [ARROW_LEFT, ARROW_RIGHT];
const verticalKeys = [ARROW_UP, ARROW_DOWN];
const allKeys = [...horizontalKeys, ...verticalKeys];

export const Composite: ParentComponent<
  JSX.HTMLAttributes<HTMLElement> & CompositeProps
> = (props) => {
  const [internalActiveIndex, internalSetActiveIndex] = createSignal(0);
  const [_, local, compositeProps] = splitProps(
    props,
    ['children'],
    [
      'orientation',
      'loop',
      'cols',
      'activeIndex',
      'onNavigate',
      'disabledIndices',
    ],
  );
  const mergedProps = mergeProps(
    {
      orientation: 'both',
      loop: true,
      cols: 1,
      activeIndex: internalActiveIndex,
      onNavigate: internalSetActiveIndex,
    } as Required<
      Pick<
        CompositeProps,
        'orientation' | 'loop' | 'cols' | 'activeIndex' | 'onNavigate'
      >
    >,
    local,
  );

  const {orientation, loop, cols, disabledIndices, activeIndex, onNavigate} =
    destructure(mergedProps, {normalize: true});

  const listContext = createFloatingListContext<CompositeContextProps>({
    activeIndex,
    onNavigate,
  });

  const isGrid = createMemo(() => cols() > 1);

  function handleKeyDown(event: KeyboardEvent) {
    if (!allKeys.includes(event.key)) return;
    const elementsRef = listContext.items();

    const minIndex = getMinIndex(elementsRef, disabledIndices?.());
    const maxIndex = getMaxIndex(elementsRef, disabledIndices?.());
    const prevIndex = activeIndex();

    let nextIndex = activeIndex();

    if (isGrid()) {
      nextIndex = getGridNavigatedIndex(elementsRef, {
        event,
        orientation: orientation(),
        loop: loop(),
        cols: cols(),
        disabledIndices: disabledIndices?.(),
        minIndex,
        maxIndex,
        prevIndex,
      });
    }

    const toEndKeys = {
      horizontal: [ARROW_RIGHT],
      vertical: [ARROW_DOWN],
      both: [ARROW_RIGHT, ARROW_DOWN],
    }[orientation()];

    const toStartKeys = {
      horizontal: [ARROW_LEFT],
      vertical: [ARROW_UP],
      both: [ARROW_LEFT, ARROW_UP],
    }[orientation()];

    const preventedKeys = isGrid()
      ? allKeys
      : {
          horizontal: horizontalKeys,
          vertical: verticalKeys,
          both: allKeys,
        }[orientation()];

    if (
      nextIndex === activeIndex() &&
      [...toEndKeys, ...toStartKeys].includes(event.key)
    ) {
      if (loop() && nextIndex === maxIndex && toEndKeys.includes(event.key)) {
        nextIndex = minIndex;
      } else if (
        loop() &&
        nextIndex === minIndex &&
        toStartKeys.includes(event.key)
      ) {
        nextIndex = maxIndex;
      } else {
        nextIndex = findNonDisabledIndex(elementsRef, {
          startingIndex: nextIndex,
          decrement: toStartKeys.includes(event.key),
          disabledIndices: disabledIndices?.(),
        });
      }
    }

    if (
      nextIndex !== activeIndex() &&
      !isIndexOutOfBounds(elementsRef, nextIndex)
    ) {
      event.stopPropagation();

      if (preventedKeys.includes(event.key)) {
        event.preventDefault();
      }

      onNavigate(nextIndex);

      // Wait for FocusManager `returnFocus` to execute.
      queueMicrotask(() => {
        enqueueFocus(elementsRef[nextIndex]);
      });
    }
  }

  const computedProps = createMemo(() => {
    const orientationRef = orientation();
    return {
      ...compositeProps,
      'aria-orientation':
        orientationRef === 'both' ? undefined : orientationRef,
      onKeyDown(e) {
        typeof compositeProps.onKeyDown === 'function' &&
          compositeProps.onKeyDown(e);
        handleKeyDown(e);
      },
    } as Omit<JSX.HTMLAttributes<HTMLElement>, 'ref'>;
  });

  return (
    <FloatingList context={listContext}>
      <Show
        when={!props.render}
        fallback={
          <>
            {untrack(() => {
              props.render?.(computedProps);
            })}
          </>
        }
      >
        <div {...computedProps()}>{_.children}</div>
      </Show>
    </FloatingList>
  );
};

export const CompositeItem: ParentComponent<
  JSX.HTMLAttributes<HTMLElement | HTMLDivElement> & {
    render?: RenderProp;
  }
> = (props) => {
  const [ref, setRef] = createSignal<HTMLElement | HTMLDivElement | null>(null);
  const [local, itemProps] = splitProps(props, ['render', 'children']);
  const context = useListItem<CompositeContextProps>(ref);

  const isActive = createMemo(
    () => context.activeIndex() === context.getItemIndex(ref()),
  );

  const computedProps = createMemo(() => {
    const index = context.getItemIndex(ref());

    return {
      ...itemProps,
      ref: (el: HTMLElement | HTMLDivElement) => {
        setRef(el);
        typeof itemProps.ref === 'function'
          ? itemProps.ref(el)
          : // eslint-disable-next-line solid/reactivity
            (itemProps.ref = el);
      },
      tabIndex: isActive() ? 0 : -1,
      'data-active': isActive() ? '' : undefined,
      onFocus(
        e: FocusEvent & {
          currentTarget: HTMLElement | HTMLDivElement;
          target: Element;
        },
      ) {
        itemProps.onFocus &&
          typeof itemProps.onFocus === 'function' &&
          itemProps.onFocus(e);
        context.onNavigate(index);
      },
    };
  });

  return (
    <Show
      when={!local.render}
      fallback={<>{untrack(() => local.render?.(computedProps))}</>}
    >
      <div id="test" {...computedProps()}>
        {local.children}
      </div>
    </Show>
  );
};

// packages/react/src/components/Composite.tsx
import * as React from 'react';

import {useMergeRefs} from '../hooks/useMergeRefs';
import {
  ARROW_DOWN,
  ARROW_LEFT,
  ARROW_RIGHT,
  ARROW_UP,
  findNonDisabledIndex,
  getGridNavigatedIndex,
  getMaxIndex,
  getMinIndex,
  isIndexOutOfBounds,
} from '../utils/composite';
import {enqueueFocus} from '../utils/enqueueFocus';
import {FloatingList, useListItem} from './FloatingList';

const CompositeContext = React.createContext<{
  activeIndex: number;
  setActiveIndex: (index: number) => void;
}>({
  activeIndex: 0,
  setActiveIndex: () => {},
});

type RenderProp =
  | JSX.Element
  | ((props: React.HTMLAttributes<HTMLElement>) => JSX.Element);

interface CompositeProps {
  render?: RenderProp;
  orientation?: 'horizontal' | 'vertical' | 'both';
  loop?: boolean;
  cols?: number;
  disabledIndices?: number[];
}

const horizontalKeys = ['ArrowLeft', 'ArrowRight'];
const verticalKeys = ['ArrowUp', 'ArrowDown'];
const allKeys = [...horizontalKeys, ...verticalKeys];

export const Composite = React.forwardRef<
  HTMLElement,
  React.HTMLProps<HTMLElement> & CompositeProps
>(function Composite(
  {
    render,
    orientation = 'both',
    loop = true,
    cols = 1,
    disabledIndices,
    ...props
  },
  forwardedRef
) {
  const [activeIndex, setActiveIndex] = React.useState(0);
  const elementsRef = React.useRef<Array<HTMLDivElement | null>>([]);
  const renderElementProps =
    render && typeof render !== 'function' ? render.props : {};
  const contextValue = React.useMemo(
    () => ({activeIndex, setActiveIndex}),
    [activeIndex]
  );

  function handleKeyDown(event: React.KeyboardEvent<HTMLDivElement>) {
    if (!allKeys.includes(event.key)) return;

    const minIndex = getMinIndex(elementsRef, disabledIndices);
    const maxIndex = getMaxIndex(elementsRef, disabledIndices);
    const prevIndex = activeIndex;

    let nextIndex = activeIndex;

    // Grid navigation.
    if (cols > 1) {
      nextIndex = getGridNavigatedIndex(elementsRef, {
        event,
        orientation,
        loop,
        cols,
        disabledIndices,
        minIndex,
        maxIndex,
        prevIndex,
      });

      if (orientation === 'both') {
        setActiveIndex(nextIndex);
        return;
      }
    }

    const toEndKeys = {
      horizontal: [ARROW_RIGHT],
      vertical: [ARROW_DOWN],
      both: [ARROW_RIGHT, ARROW_DOWN],
    }[orientation];

    const toStartKeys = {
      horizontal: [ARROW_LEFT],
      vertical: [ARROW_UP],
      both: [ARROW_LEFT, ARROW_UP],
    }[orientation];

    const preventedKeys = {
      horizontal: horizontalKeys,
      vertical: verticalKeys,
      both: allKeys,
    }[orientation];

    if (
      nextIndex === activeIndex &&
      [...toEndKeys, ...toStartKeys].includes(event.key)
    ) {
      if (nextIndex === maxIndex && toEndKeys.includes(event.key)) {
        nextIndex = minIndex;
      } else if (nextIndex === minIndex && toStartKeys.includes(event.key)) {
        nextIndex = maxIndex;
      } else {
        nextIndex = findNonDisabledIndex(elementsRef, {
          startingIndex: nextIndex,
          decrement: toStartKeys.includes(event.key),
          disabledIndices,
        });
      }
    }

    if (
      nextIndex !== activeIndex &&
      !isIndexOutOfBounds(elementsRef, nextIndex)
    ) {
      event.stopPropagation();

      if (preventedKeys.includes(event.key)) {
        event.preventDefault();
      }

      setActiveIndex(nextIndex);

      // Wait for FocusManager `returnFocus` to execute.
      queueMicrotask(() => {
        enqueueFocus(elementsRef.current[nextIndex]);
      });
    }
  }

  const computedProps = {
    ...props,
    ...renderElementProps,
    ref: forwardedRef,
    'aria-orientation': orientation === 'both' ? undefined : orientation,
    onKeyDown(e: React.KeyboardEvent<any>) {
      props.onKeyDown?.(e);
      renderElementProps.onKeyDown?.(e);
      handleKeyDown(e);
    },
  };

  let jsx = null;
  if (typeof render === 'function') {
    jsx = render(computedProps);
  } else if (render) {
    jsx = React.cloneElement(render, computedProps);
  } else {
    jsx = <span {...computedProps} />;
  }

  return (
    <CompositeContext.Provider value={contextValue}>
      <FloatingList elementsRef={elementsRef}>{jsx}</FloatingList>
    </CompositeContext.Provider>
  );
});

export const CompositeItem = React.forwardRef<
  HTMLElement,
  React.HTMLProps<HTMLElement> & {render?: RenderProp}
>(function CompositeItem({render, ...props}, forwardedRef) {
  const renderElementProps =
    render && typeof render !== 'function' ? render.props : {};

  const {activeIndex, setActiveIndex} = React.useContext(CompositeContext);
  const {ref, index} = useListItem();
  const mergedRef = useMergeRefs([ref, forwardedRef, renderElementProps.ref]);
  const isActive = activeIndex === index;

  const computedProps = {
    ...props,
    ...renderElementProps,
    ref: mergedRef,
    tabIndex: isActive ? 0 : -1,
    'data-active': isActive ? '' : undefined,
    onFocus(e: React.FocusEvent<any>) {
      props.onFocus?.(e);
      renderElementProps.onFocus?.(e);
      setActiveIndex(index);
    },
  };

  let jsx = null;
  if (typeof render === 'function') {
    jsx = render(computedProps);
  } else if (render) {
    jsx = React.cloneElement(render, computedProps);
  } else {
    jsx = <span {...computedProps} />;
  }

  return jsx;
});
