// packages/solid/src/components/FloatingList.tsx
import {
  Accessor,
  createContext,
  createMemo,
  createSignal,
  JSX,
  onCleanup,
  onMount,
  ParentProps,
  useContext,
} from 'solid-js';

function sortByDocumentPosition(a: Node, b: Node) {
  const position = a.compareDocumentPosition(b);

  if (
    position & Node.DOCUMENT_POSITION_FOLLOWING ||
    position & Node.DOCUMENT_POSITION_CONTAINED_BY
  ) {
    return -1;
  }

  if (
    position & Node.DOCUMENT_POSITION_PRECEDING ||
    position & Node.DOCUMENT_POSITION_CONTAINS
  ) {
    return 1;
  }

  return 0;
}

function areMapsEqual(
  map1: Map<Node, number | null>,
  map2: Map<Node, number | null>
) {
  if (map1.size !== map2.size) {
    return false;
  }
  for (const [key, value] of map1.entries()) {
    if (value !== map2.get(key)) {
      return false;
    }
  }
  return true;
}

export const FloatingListContext = createContext<{
  register: (node: HTMLElement) => void;
  unregister: (node: HTMLElement) => void;
  map: Accessor<Array<HTMLElement | null>>;
  elementsRef: Accessor<Array<HTMLElement | null>>;
  labelsRef?: Array<string | null>;
  // map: Accessor<Map<Node, number | null>>;
  // map: Map<Node, number | null>;
}>({
  register: () => {},
  unregister: () => {},
  map: () => [],
  elementsRef: () => [],
});

interface FloatingListProps {
  elementsRef: Array<HTMLElement>;
  labelsRef?: Array<string>;
}

/**
 * Provides context for a list of items within the floating element.
 * @see https://floating-ui.com/docs/FloatingList
 */
export function FloatingList(
  // 	{
  //   children,
  //   elementsRef,
  //   labelsRef,
  // }
  props: ParentProps //<FloatingListProps>
): JSX.Element {
  // const [map, setMap] = createSignal(new Map<Node, number | null>());
  // const map = new ReactiveMap<HTMLElement, number | null>();
  // const register = (node: HTMLElement) => {
  //   map.set(node, null);
  // };

  // const unregister = (node: HTMLElement) => {
  //   map.delete(node);
  // };
  const [map, setMap] = createSignal<Array<HTMLElement>>([]);
  const register = (node: HTMLElement) => {
    setMap((prev) => [...prev, node].sort(sortByDocumentPosition));
  };

  const unregister = (node: HTMLElement) => {
    setMap((prev) => [...prev.filter((o) => o !== node)]);
  };

  // createEffect(() => {
  //   const newMap = new Map(map);
  //   const nodes = Array.from(newMap.keys()).sort(sortByDocumentPosition);

  //   nodes.forEach((node, index) => {
  //     newMap.set(node, index);
  //   });

  //   if (!areMapsEqual(map, newMap)) {
  //     map(newMap);
  //   }
  // });
  // const elementsRef = createMemo(() => Array.from(map.keys()));
  return (
    <FloatingListContext.Provider
      value={{
        register,
        unregister,
        map,
        elementsRef: map,
        // labelsRef: props.labelsRef,
      }}
    >
      {props.children}
    </FloatingListContext.Provider>
  );
}
export default FloatingList;

export interface UseListItemProps {
  label?: string | null;
}

// export function useListItem({label}: UseListItemProps = {}): Accessor<{
//   ref: Accessor<HTMLElement>;
//   index: number;
// }> {
//   const [index, setIndex] = createSignal<number | null>(null);
//   // const [item, setItem] = createSignal<Node|null>(null);
//   // const [list, setList] = createSignal<Array<Node>>([]);
//   // const addToList = (item:Node) => {
//   // 		if (!list().includes(item)) setList(prev =>[...prev, item]);
//   // }
//   // const removeFromList = (item:Node) => {
//   // 		if (list().includes(item)) setList(prev => [...prev.filter(i => i !== item)]);
//   // }
//   let componentRef: Node | null = null;
//   const context = useContext(FloatingListContext);
//   const {
//     register,
//     unregister,
//     // map, elementsRef, labelsRef
//   } = context;

//   const ref = (node: HTMLElement | null) => {
//     console.log('####################################    REF');

//     componentRef = node;
//     // node && addToList(node);
//     const indexRef = index();
//     if (indexRef !== null) {
//       context.elementsRef[indexRef] = node;
//       console.log('useListItem: context.elementsRef', {
//         elementsRef: context.elementsRef,
//         indexRef,
//       });
//       if (context.labelsRef) {
//         const isLabelDefined = label !== undefined;
//         context.labelsRef[indexRef] = isLabelDefined
//           ? label
//           : node?.textContent ?? null;
//       }
//     }
//   };
//   // onCleanup(()=> removeFromList(componentRef))
//   createEffect(() => {
//     const node = componentRef;
//     console.log('useListItem: componentRef', {
//       componentRef,
//       node,
//       // id: node?.ATTRIBUTE_NODE.,
//     });
//     if (node) {
//       register(node);
//     }
//     onCleanup(() => {
//       node && unregister(node);
//     });
//   });

//   createEffect(() => {
//     const index = componentRef ? context.map.get(componentRef) : null;
//     if (index != null) {
//       setIndex(index);
//     }
//   });

//   return () => ({
//     ref,
//     index: index() == null ? -1 : (index() as number),
//   });
// }

export function useListItem(ref: Accessor<HTMLElement | null>) {
  const listItemContext = useContext(FloatingListContext);
  onMount(() => {
    const itemRef = ref();
    itemRef && listItemContext.register(itemRef);
  });
  onCleanup(() => {
    const itemRef = ref();
    itemRef && listItemContext.unregister(itemRef);
  });
  const idx = createMemo(() => {
    const itemRef = ref();
    const index = itemRef ? listItemContext.map().indexOf(itemRef) : null;
    itemRef &&
      console.log({
        ref: ref(),
        idx: listItemContext.map().indexOf(itemRef),
        map: listItemContext.map,
      });
    return index ?? null;
  });

  return idx;
}

export function useFloatingList() {
  return useContext(FloatingListContext);
}

export function useList() {
  const [items, setItems] = createSignal<Array<HTMLElement>>([]);
  const register = (node: HTMLElement) => {
    setItems((prev) => [...prev, node].sort(sortByDocumentPosition));
  };

  const unregister = (node: HTMLElement) => {
    setItems((prev) => [...prev.filter((o) => o !== node)]);
  };

  return {
    items,
    register,
    unregister,
  };
}

// packages/react/src/components/FloatingList.tsx
import * as React from 'react';
import useModernLayoutEffect from 'use-isomorphic-layout-effect';

function sortByDocumentPosition(a: Node, b: Node) {
  const position = a.compareDocumentPosition(b);

  if (
    position & Node.DOCUMENT_POSITION_FOLLOWING ||
    position & Node.DOCUMENT_POSITION_CONTAINED_BY
  ) {
    return -1;
  }

  if (
    position & Node.DOCUMENT_POSITION_PRECEDING ||
    position & Node.DOCUMENT_POSITION_CONTAINS
  ) {
    return 1;
  }

  return 0;
}

function areMapsEqual(
  map1: Map<Node, number | null>,
  map2: Map<Node, number | null>,
) {
  if (map1.size !== map2.size) {
    return false;
  }
  for (const [key, value] of map1.entries()) {
    if (value !== map2.get(key)) {
      return false;
    }
  }
  return true;
}

export const FloatingListContext = React.createContext<{
  register: (node: Node) => void;
  unregister: (node: Node) => void;
  map: Map<Node, number | null>;
  elementsRef: React.MutableRefObject<Array<HTMLElement | null>>;
  labelsRef?: React.MutableRefObject<Array<string | null>>;
}>({
  register: () => {},
  unregister: () => {},
  map: new Map(),
  elementsRef: {current: []},
});

interface FloatingListProps {
  children: React.ReactNode;
  /**
   * A ref to the list of HTML elements, ordered by their index.
   * `useListNavigation`'s `listRef` prop.
   */
  elementsRef: React.MutableRefObject<Array<HTMLElement | null>>;
  /**
   * A ref to the list of element labels, ordered by their index.
   * `useTypeahead`'s `listRef` prop.
   */
  labelsRef?: React.MutableRefObject<Array<string | null>>;
}

/**
 * Provides context for a list of items within the floating element.
 * @see https://floating-ui.com/docs/FloatingList
 */
export function FloatingList(props: FloatingListProps): React.JSX.Element {
  const {children, elementsRef, labelsRef} = props;

  const [nodes, setNodes] = React.useState(() => new Set<Node>());

  const register = React.useCallback((node: Node) => {
    setNodes((prevMap) => new Set(prevMap).add(node));
  }, []);

  const unregister = React.useCallback((node: Node) => {
    setNodes((prevMap) => {
      const map = new Set(prevMap);
      map.delete(node);
      return map;
    });
  }, []);

  const map = React.useMemo(() => {
    const newMap = new Map<Node, number>();
    const sortedNodes = Array.from(nodes.keys()).sort(sortByDocumentPosition);

    sortedNodes.forEach((node, index) => {
      newMap.set(node, index);
    });

    return newMap;
  }, [nodes]);

  return (
    <FloatingListContext.Provider
      value={React.useMemo(
        () => ({register, unregister, map, elementsRef, labelsRef}),
        [register, unregister, map, elementsRef, labelsRef],
      )}
    >
      {children}
    </FloatingListContext.Provider>
  );
}

export interface UseListItemProps {
  label?: string | null;
}

/**
 * Used to register a list item and its index (DOM position) in the
 * `FloatingList`.
 * @see https://floating-ui.com/docs/FloatingList#uselistitem
 */
export function useListItem(props: UseListItemProps = {}): {
  ref: (node: HTMLElement | null) => void;
  index: number;
} {
  const {label} = props;

  const {register, unregister, map, elementsRef, labelsRef} =
    React.useContext(FloatingListContext);

  const [index, setIndex] = React.useState<number | null>(null);

  const componentRef = React.useRef<Node | null>(null);

  const ref = React.useCallback(
    (node: HTMLElement | null) => {
      componentRef.current = node;

      if (index !== null) {
        elementsRef.current[index] = node;
        if (labelsRef) {
          const isLabelDefined = label !== undefined;
          labelsRef.current[index] = isLabelDefined
            ? label
            : node?.textContent ?? null;
        }
      }
    },
    [index, elementsRef, labelsRef, label],
  );

  useModernLayoutEffect(() => {
    const node = componentRef.current;
    if (node) {
      register(node);
      return () => {
        unregister(node);
      };
    }
  }, [register, unregister]);

  useModernLayoutEffect(() => {
    const index = componentRef.current ? map.get(componentRef.current) : null;
    if (index != null) {
      setIndex(index);
    }
  }, [map]);

  return React.useMemo(
    () => ({
      ref,
      index: index == null ? -1 : index,
    }),
    [index, ref],
  );
}
