// packages/react/src/types.ts
import type {
  ComputePositionReturn,
  UseFloatingOptions as UsePositionOptions,
  UseFloatingReturn as UsePositionFloatingReturn,
  VirtualElement,
} from '@floating-ui/react-dom';
import * as React from 'react';

import type {DismissPayload} from './hooks/useDismiss';

export * from '.';
export {Props as FloatingArrowProps} from './components/FloatingArrow';
export {Props as UseClickProps} from './hooks/useClick';
export {Props as UseClientPointProps} from './hooks/useClientPoint';
export {Props as UseDismissProps} from './hooks/useDismiss';
export {Props as UseFocusProps} from './hooks/useFocus';
export {Props as UseHoverProps} from './hooks/useHover';
export {Props as UseListNavigationProps} from './hooks/useListNavigation';
export {Props as UseRoleProps} from './hooks/useRole';
export {
  Props as UseTransitionStatusProps,
  UseTransitionStylesProps,
} from './hooks/useTransition';
export {Props as UseTypeaheadProps} from './hooks/useTypeahead';
export {InnerProps, UseInnerOffsetProps} from './inner';
export type {
  AlignedPlacement,
  Alignment,
  ArrowOptions,
  AutoPlacementOptions,
  AutoUpdateOptions,
  Axis,
  Boundary,
  ClientRectObject,
  ComputePositionConfig,
  ComputePositionReturn,
  Coords,
  DetectOverflowOptions,
  Dimensions,
  ElementContext,
  ElementRects,
  Elements,
  FlipOptions,
  FloatingElement,
  HideOptions,
  InlineOptions,
  Length,
  Middleware,
  MiddlewareArguments,
  MiddlewareData,
  MiddlewareReturn,
  MiddlewareState,
  NodeScroll,
  OffsetOptions,
  Padding,
  Placement,
  Platform,
  Rect,
  ReferenceElement,
  RootBoundary,
  ShiftOptions,
  Side,
  SideObject,
  SizeOptions,
  Strategy,
  VirtualElement,
} from '@floating-ui/react-dom';
export {
  arrow,
  autoPlacement,
  autoUpdate,
  computePosition,
  detectOverflow,
  flip,
  getOverflowAncestors,
  hide,
  inline,
  limitShift,
  offset,
  platform,
  shift,
  size,
} from '@floating-ui/react-dom';

type Prettify<T> = {
  [K in keyof T]: T[K];
  // eslint-disable-next-line @typescript-eslint/ban-types
} & {};

export type NarrowedElement<T> = T extends Element ? T : Element;

export interface ExtendedRefs<RT> {
  reference: React.MutableRefObject<ReferenceType | null>;
  floating: React.MutableRefObject<HTMLElement | null>;
  domReference: React.MutableRefObject<NarrowedElement<RT> | null>;
  setReference: (node: RT | null) => void;
  setFloating: (node: HTMLElement | null) => void;
  setPositionReference: (node: ReferenceType | null) => void;
}

export interface ExtendedElements<RT> {
  reference: ReferenceType | null;
  floating: HTMLElement | null;
  domReference: NarrowedElement<RT> | null;
}

export interface FloatingEvents {
  emit<T extends string>(
    event: T,
    data?: T extends 'dismiss' ? DismissPayload : any
  ): void;
  on(event: string, handler: (data: any) => void): void;
  off(event: string, handler: (data: any) => void): void;
}

export interface ContextData {
  openEvent?: MouseEvent | PointerEvent | FocusEvent;
  /** @deprecated use `onTypingChange` prop in `useTypeahead` */
  typing?: boolean;
  [key: string]: any;
}

export type FloatingContext<RT extends ReferenceType = ReferenceType> =
  Prettify<
    Omit<UsePositionFloatingReturn<RT>, 'refs' | 'elements'> & {
      open: boolean;
      onOpenChange: (open: boolean) => void;
      events: FloatingEvents;
      dataRef: React.MutableRefObject<ContextData>;
      nodeId: string | undefined;
      floatingId: string;
      refs: ExtendedRefs<RT>;
      elements: ExtendedElements<RT>;
    }
  >;

export interface FloatingNodeType<RT extends ReferenceType = ReferenceType> {
  id: string;
  parentId: string | null;
  context?: FloatingContext<RT>;
}

export interface FloatingTreeType<RT extends ReferenceType = ReferenceType> {
  nodesRef: React.MutableRefObject<Array<FloatingNodeType<RT>>>;
  events: FloatingEvents;
  addNode: (node: FloatingNodeType) => void;
  removeNode: (node: FloatingNodeType) => void;
}

export interface ElementProps {
  reference?: React.HTMLProps<Element>;
  floating?: React.HTMLProps<HTMLElement>;
  item?: React.HTMLProps<HTMLElement>;
}

export type ReferenceType = Element | VirtualElement;

export type UseFloatingData = Prettify<ComputePositionReturn>;

export type UseFloatingReturn<RT extends ReferenceType = ReferenceType> =
  Prettify<
    UseFloatingData & {
      update: () => void;
      context: FloatingContext<RT>;
      refs: ExtendedRefs<RT>;
      elements: ExtendedElements<RT>;
      isPositioned: boolean;
      floatingStyles: React.CSSProperties;
    }
  >;

export interface UseFloatingOptions<RT extends ReferenceType = ReferenceType>
  extends UsePositionOptions<RT> {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  nodeId: string;
}

// packages/solid/src/types.ts
import type {
  ComputePositionConfig,
  ComputePositionReturn,
  Padding,
  ReferenceElement,
  VirtualElement,
} from '@floating-ui/dom';
import type {Accessor, JSX} from 'solid-js';

import {DismissPayload} from './hooks/useDismiss';

export {arrow} from './arrow';
export {useFloating} from './hooks/useFloating';
export type {
  AlignedPlacement,
  Alignment,
  AutoPlacementOptions,
  AutoUpdateOptions,
  Axis,
  Boundary,
  ClientRectObject,
  ComputePositionConfig,
  ComputePositionReturn,
  Coords,
  DetectOverflowOptions,
  Dimensions,
  ElementContext,
  ElementRects,
  Elements,
  FlipOptions,
  FloatingElement,
  HideOptions,
  InlineOptions,
  Length,
  Middleware,
  MiddlewareArguments,
  MiddlewareData,
  MiddlewareReturn,
  MiddlewareState,
  NodeScroll,
  OffsetOptions,
  Padding,
  Placement,
  Platform,
  Rect,
  ReferenceElement,
  RootBoundary,
  ShiftOptions,
  Side,
  SideObject,
  SizeOptions,
  Strategy,
  VirtualElement,
} from '@floating-ui/dom';
export {
  autoPlacement,
  autoUpdate,
  computePosition,
  detectOverflow,
  flip,
  getOverflowAncestors,
  hide,
  inline,
  limitShift,
  offset,
  platform,
  shift,
  size,
} from '@floating-ui/dom';

type Prettify<T> = {
  [K in keyof T]: T[K];
  // eslint-disable-next-line @typescript-eslint/ban-types
} & {};

export type UseFloatingData = Prettify<
  ComputePositionReturn & {isPositioned: boolean}
>;

export type ReferenceType = Element | VirtualElement;

export type UseFloatingReturn<R extends ReferenceType = ReferenceType> =
  Prettify<
    UseFloatingData & {
      /**
       * Update the position of the floating element, re-rendering the component
       * if required.
       */
      update: () => void;
      /**
       * Pre-configured positioning styles to apply to the floating element.
       */
      floatingStyles: JSX.CSSProperties;
      /**
       * Object containing the reference and floating refs and reactive setters.
       */
      refs: ExtendedRefs<R>;
      // {
      //   /**
      //    * A reactive reference element.
      //    */
      //   reference: Accessor<R | null>;
      //   /**
      //    * A reactive floating element.
      //    */
      //   floating: Accessor<F | null>;
      //   /**
      //    * A callback to set the reference element (reactive).
      //    */
      //   setReference: (node: R | null) => void;
      //   /**
      //    * A callback to set the floating element (reactive).
      //    */
      //   setFloating: (node: F | null) => void;
      // };
      context: Accessor<FloatingContext<R>>;
      // elements: {
      //   reference?: R | null;
      //   floating?: F | null;
      // };
    }
  >;

export type UseFloatingOptions<R extends ReferenceType = ReferenceType> =
  Prettify<
    Partial<ComputePositionConfig> & {
      /**
       * A callback invoked when both the reference and floating elements are
       * mounted, and cleaned up when either is unmounted. This is useful for
       * setting up event listeners (e.g. pass `autoUpdate`).
       */
      whileElementsMounted?: (
        reference: ReferenceElement | R | null,
        floating: HTMLElement | null,
        update: () => void
      ) => () => void;
      // elements?: {
      //   reference?: R | null;
      //   floating?: F | null;
      // };
      /**
       * The `open` state of the floating element to synchronize with the
       * `isPositioned` value.
       */
      open?: Accessor<boolean>;
      /**
       * Whether to use `transform` for positioning instead of `top` and `left`
       * (layout) in the `floatingStyles` object.
       */
      transform?: boolean;
      onOpenChange?: (open: boolean, event?: Event) => void;
      nodeId?: string;
    }
  >;

export type ArrowOptions = {
  /**
   * The arrow element or template ref to be positioned.
   * @required
   */
  element: Accessor<HTMLElement | undefined>;
  /**
   * The padding between the arrow element and the floating element edges. Useful when the floating element has rounded corners.
   * @default 0
   */
  padding?: Padding;
};

export type NarrowedElement<T> = T extends Element ? T : Element;

export type ExtendedRefs<R> = {
  reference: Accessor<R | null>;
  floating: Accessor<HTMLElement | null>;
  // domReference: NarrowedElement<RT> | null;
  setReference: (node: R | null) => void;
  setFloating: (node: HTMLElement | null) => void;
  // setPositionReference: (node: ReferenceType | null) => void;
};

export interface ExtendedElements<R extends ReferenceType = ReferenceType> {
  reference: Accessor<R | null>;
  floating: Accessor<HTMLElement | null>;
  // domReference: NarrowedElement<RT> | null;
}

export interface FloatingEvents {
  emit<T extends string>(
    event: T,
    data?: T extends 'dismiss' ? DismissPayload : any
  ): void;
  on(event: string, handler: (data: any) => void): void;
  off(event: string, handler: (data: any) => void): void;
}

export interface ContextData {
  openEvent?: Event;
  [key: string]: any;
}

export type FloatingContext<R extends ReferenceType = ReferenceType> = Omit<
  UseFloatingReturn<R>,
  'elements' | 'context'
> & {
  open: Accessor<boolean>;
  onOpenChange: (open: boolean, event?: Event) => void;
  events: FloatingEvents;
  dataRef: ContextData; //React.MutableRefObject<ContextData>;
  nodeId: string | undefined;
  floatingId: string;
  // refs: ExtendedRefs<R, F>;
  // elements: ExtendedElements<R>;
};

export interface FloatingNodeType<R extends ReferenceType = ReferenceType> {
  id: string;
  parentId: string | null;
  context?: FloatingContext<R>;
}

export interface FloatingTreeType<R extends ReferenceType = ReferenceType> {
  nodesRef: Array<FloatingNodeType<R>>;
  events: FloatingEvents;
  addNode: (node: FloatingNodeType) => void;
  removeNode: (node: FloatingNodeType) => void;
}

export interface ElementProps {
  reference?: JSX.HTMLAttributes<Element>;
  floating?: JSX.HTMLAttributes<HTMLElement>;
  item?: JSX.HTMLAttributes<HTMLElement>;
}
