// packages/solid/src/hooks/useClick.ts
import {isHTMLElement} from '@floating-ui/utils/dom';
import {
  isMouseLikePointerType,
  isTypeableElement,
} from '@floating-ui/utils/react';
import {Accessor, mergeProps} from 'solid-js';

import type {ElementProps, FloatingContext, ReferenceType} from '../types';

function isButtonTarget(event: KeyboardEvent) {
  return isHTMLElement(event.target) && event.target.tagName === 'BUTTON';
}

function isSpaceIgnored(element: Element | null) {
  return isTypeableElement(element);
}

export interface UseClickProps {
  enabled?: Accessor<boolean>;
  event?: 'click' | 'mousedown';
  toggle?: Accessor<boolean>;
  ignoreMouse?: Accessor<boolean>;
  keyboardHandlers?: Accessor<boolean>;
}
type PointerType = 'mouse' | 'pen' | 'touch';
/**
 * Opens or closes the floating element when clicking the reference element.
 * @see https://floating-ui.com/docs/useClick
 */
export function useClick<RT extends ReferenceType = ReferenceType>(
  context: FloatingContext<RT>,
  props: UseClickProps = {}
): ElementProps {
  const {open, onOpenChange, dataRef, refs} = context;
  const mergedProps = mergeProps(
    {
      enabled: () => true,
      event: 'click',
      toggle: () => true,
      ignoreMouse: () => false,
      keyboardHandlers: () => true,
    },
    props
  );
  const {enabled, toggle, ignoreMouse, keyboardHandlers} = mergedProps;
  const eventOption = mergedProps.event;
  let pointerTypeRef: PointerType | undefined;
  let didKeyDownRef = false;

  if (!enabled) return {};

  return {
    reference: {
      onPointerDown(event) {
        pointerTypeRef = event.pointerType as PointerType;
      },
      onMouseDown(event) {
        // Ignore all buttons except for the "main" button.
        // https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button
        if (event.button !== 0) {
          return;
        }

        if (isMouseLikePointerType(pointerTypeRef, true) && ignoreMouse()) {
          return;
        }

        if (eventOption === 'click') {
          return;
        }

        if (
          open() &&
          toggle() &&
          (dataRef.openEvent ? dataRef.openEvent.type === 'mousedown' : true)
        ) {
          onOpenChange(false, event);
        } else {
          // Prevent stealing focus from the floating element
          event.preventDefault();
          onOpenChange(true, event);
        }
      },
      onClick(event) {
        if (eventOption === 'mousedown' && pointerTypeRef) {
          pointerTypeRef = undefined;
          return;
        }

        if (isMouseLikePointerType(pointerTypeRef, true) && ignoreMouse()) {
          return;
        }

        if (
          open() &&
          toggle() &&
          (dataRef.openEvent ? dataRef.openEvent.type === 'click' : true)
        ) {
          onOpenChange(false, event);
        } else {
          onOpenChange(true, event);
        }
      },
      onKeyDown(event) {
        pointerTypeRef = undefined;

        if (
          event.defaultPrevented ||
          !keyboardHandlers ||
          isButtonTarget(event)
        ) {
          return;
        }

        if (event.key === ' ' && !isSpaceIgnored(refs.reference() as Element)) {
          // Prevent scrolling
          event.preventDefault();
          didKeyDownRef = true;
        }

        if (event.key === 'Enter') {
          if (open() && toggle()) {
            onOpenChange(false, event);
          } else {
            onOpenChange(true, event);
          }
        }
      },
      onKeyUp(event) {
        if (
          event.defaultPrevented ||
          !keyboardHandlers ||
          isButtonTarget(event) ||
          isSpaceIgnored(refs.reference() as Element)
        ) {
          return;
        }

        if (event.key === ' ' && didKeyDownRef) {
          didKeyDownRef = false;
          if (open() && toggle()) {
            onOpenChange(false, event);
          } else {
            onOpenChange(true, event);
          }
        }
      },
    },
  };
}

// packages/react-dom-interactions/src/hooks/useClick.ts
import type {ElementProps, FloatingContext, ReferenceType} from '../types';
import * as React from 'react';
import {isHTMLElement} from '../utils/is';
import {isTypeableElement} from '../utils/isTypeableElement';

export interface Props {
  enabled?: boolean;
  pointerDown?: boolean;
  toggle?: boolean;
  ignoreMouse?: boolean;
}

/**
 * Adds click event listeners that change the open state.
 * @see https://floating-ui.com/docs/useClick
 */
export const useClick = <RT extends ReferenceType = ReferenceType>(
  {open, onOpenChange, dataRef, refs}: FloatingContext<RT>,
  {
    enabled = true,
    pointerDown = false,
    toggle = true,
    ignoreMouse = false,
  }: Props = {}
): ElementProps => {
  const pointerTypeRef = React.useRef<'mouse' | 'pen' | 'touch'>();

  function isButton() {
    return (
      isHTMLElement(refs.reference.current) &&
      refs.reference.current.tagName === 'BUTTON'
    );
  }

  function isSpaceIgnored() {
    return isTypeableElement(refs.reference.current);
  }

  if (!enabled) {
    return {};
  }

  return {
    reference: {
      onPointerDown(event) {
        // Ignore all buttons except for the "main" button.
        // https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button
        if (event.button !== 0) {
          return;
        }

        pointerTypeRef.current = event.pointerType;

        if (pointerTypeRef.current === 'mouse' && ignoreMouse) {
          return;
        }

        if (!pointerDown) {
          return;
        }

        if (open) {
          if (toggle && dataRef.current.openEvent?.type === 'pointerdown') {
            onOpenChange(false);
          }
        } else {
          onOpenChange(true);
        }

        dataRef.current.openEvent = event.nativeEvent;
      },
      onClick(event) {
        if (pointerDown && pointerTypeRef.current) {
          pointerTypeRef.current = undefined;
          return;
        }

        if (pointerTypeRef.current === 'mouse' && ignoreMouse) {
          return;
        }

        if (open) {
          if (toggle && dataRef.current.openEvent?.type === 'click') {
            onOpenChange(false);
          }
        } else {
          onOpenChange(true);
        }

        dataRef.current.openEvent = event.nativeEvent;
      },
      onKeyDown(event) {
        pointerTypeRef.current = undefined;

        if (isButton()) {
          return;
        }

        if (event.key === ' ' && !isSpaceIgnored()) {
          // Prvent scrolling
          event.preventDefault();
        }

        if (event.key === 'Enter') {
          if (open) {
            if (toggle) {
              onOpenChange(false);
            }
          } else {
            onOpenChange(true);
          }
        }
      },
      onKeyUp(event) {
        if (isButton() || isSpaceIgnored()) {
          return;
        }

        if (event.key === ' ') {
          if (open) {
            if (toggle) {
              onOpenChange(false);
            }
          } else {
            onOpenChange(true);
          }
        }
      },
    },
  };
};
