// packages/solid/src/hooks/useTypeahead.ts
import {stopEvent} from '@floating-ui/utils/react';
import {Accessor, createEffect, mergeProps} from 'solid-js';

import type {ElementProps, FloatingContext, ReferenceType} from '../types';

type ListType = Accessor<Array<string | null>>;

export interface UseTypeaheadProps {
  listRef: ListType;
  activeIndex: Accessor<number | null>;
  onMatch?: (index: number) => void;
  onTypingChange?: (isTyping: boolean) => void;
  enabled?: Accessor<boolean>;
  findMatch?:
    | null
    | ((
        list: Array<string | null>,
        typedString: string
      ) => string | null | undefined);
  resetMs?: number;
  ignoreKeys?: Array<string>;
  selectedIndex?: Accessor<number | null>;
}

/**
 * Provides a matching callback that can be used to focus an item as the user
 * types, often used in tandem with `useListNavigation()`.
 * @see https://floating-ui.com/docs/useTypeahead
 */
export function useTypeahead<RT extends ReferenceType = ReferenceType>(
  context: FloatingContext<RT>,
  props: UseTypeaheadProps
): ElementProps {
  const mergedProps = mergeProps(
    {
      enabled: () => true,
      findMatch: null,
      resetMs: 750,
      ignoreKeys: [],
      selectedIndex: () => null,
    } as Required<
      Pick<
        UseTypeaheadProps,
        'findMatch' | 'resetMs' | 'ignoreKeys' | 'selectedIndex' | 'enabled'
      >
    >,
    props
  );

  const {
    listRef,
    activeIndex,
    onMatch,
    onTypingChange,
    enabled,
    findMatch,
    selectedIndex,
  } = mergedProps;

  let timeoutIdRef: number;
  let stringRef = '';
  let prevIndexRef: number | null = selectedIndex() ?? activeIndex() ?? -1;
  let matchIndexRef: number | null = null;

  createEffect(() => {
    if (context.open()) {
      clearTimeout(timeoutIdRef);
      matchIndexRef = null;
      stringRef = '';
    }
  });

  createEffect(() => {
    // Sync arrow key navigation but not typeahead navigation.
    if (context.open() && stringRef === '') {
      prevIndexRef = selectedIndex() ?? activeIndex() ?? -1;
    }
  });

  function setTypingChange(value: boolean) {
    const {dataRef} = context;
    if (value) {
      if (!dataRef.typing) {
        dataRef.typing = value;
        onTypingChange?.(value);
      }
    } else {
      if (dataRef.typing) {
        dataRef.typing = value;
        onTypingChange?.(value);
      }
    }
  }

  function getMatchingIndex(
    list: Array<string | null>,
    orderedList: Array<string | null>,
    string: string
  ) {
    const str = findMatch
      ? findMatch(orderedList, string)
      : orderedList.find(
          (text) =>
            text?.toLocaleLowerCase().indexOf(string.toLocaleLowerCase()) === 0
        );

    return str ? list.indexOf(str) : -1;
  }

  function onKeyDown(event: KeyboardEvent) {
    const listContent = listRef;
    if (stringRef.length > 0 && stringRef[0] !== ' ') {
      if (getMatchingIndex(listContent(), listContent(), stringRef) === -1) {
        setTypingChange(false);
      } else if (event.key === ' ') {
        stopEvent(event);
      }
    }

    if (
      listContent() == null ||
      mergedProps.ignoreKeys.includes(event.key) ||
      // Character key.
      event.key.length !== 1 ||
      // Modifier key.
      event.ctrlKey ||
      event.metaKey ||
      event.altKey
    ) {
      return;
    }

    if (context.open() && event.key !== ' ') {
      stopEvent(event);
      setTypingChange(true);
    }

    // Bail out if the list contains a word like "llama" or "aaron". TODO
    // allow it in this case, too.
    const allowRapidSuccessionOfFirstLetter = listContent().every((text) =>
      text
        ? text[0]?.toLocaleLowerCase() !== text[1]?.toLocaleLowerCase()
        : true
    );

    // Allows the user to cycle through items that start with the same letter
    // in rapid succession.
    if (allowRapidSuccessionOfFirstLetter && stringRef === event.key) {
      stringRef = '';
      prevIndexRef = matchIndexRef;
    }

    stringRef += event.key;
    clearTimeout(timeoutIdRef);
    timeoutIdRef = setTimeout(() => {
      stringRef = '';
      prevIndexRef = matchIndexRef;
      setTypingChange(false);
    }, mergedProps.resetMs);

    const prevIndex = prevIndexRef;

    const index = getMatchingIndex(
      listContent(),
      [
        ...listContent().slice((prevIndex || 0) + 1),
        ...listContent().slice(0, (prevIndex || 0) + 1),
      ],
      stringRef
    );

    if (index !== -1) {
      onMatch?.(index);
      matchIndexRef = index;
    } else if (event.key !== ' ') {
      stringRef = '';
      setTypingChange(false);
    }
  }

  return !enabled()
    ? {}
    : {
        reference: {onKeyDown},
        floating: {
          onKeyDown,
          onKeyUp(event) {
            if (event.key === ' ') {
              setTypingChange(false);
            }
          },
        },
      };
}

// packages/react-dom-interactions/src/hooks/useTypeahead.ts
import * as React from 'react';
import useLayoutEffect from 'use-isomorphic-layout-effect';
import type {ElementProps, FloatingContext, ReferenceType} from '../types';
import {isElement} from '../utils/is';
import {stopEvent} from '../utils/stopEvent';

export interface Props {
  listRef: React.MutableRefObject<Array<string | null>>;
  activeIndex: number | null;
  onMatch?: (index: number) => void;
  enabled?: boolean;
  findMatch?:
    | null
    | ((
        list: Array<string | null>,
        typedString: string
      ) => string | null | undefined);
  resetMs?: number;
  ignoreKeys?: Array<string>;
  selectedIndex?: number | null;
}

/**
 * Provides a matching callback that can be used to focus an item as the user
 * types, often used in tandem with `useListNavigation()`.
 * @see https://floating-ui.com/docs/useTypeahead
 */
export const useTypeahead = <RT extends ReferenceType = ReferenceType>(
  {open, dataRef}: FloatingContext<RT>,
  {
    listRef,
    activeIndex,
    onMatch = () => {},
    enabled = true,
    findMatch = null,
    resetMs = 1000,
    ignoreKeys = [],
    selectedIndex = null,
  }: Props = {
    listRef: {current: []},
    activeIndex: null,
  }
): ElementProps => {
  const timeoutIdRef = React.useRef<any>();
  const stringRef = React.useRef('');
  const prevIndexRef = React.useRef<number | null>(
    selectedIndex ?? activeIndex ?? -1
  );
  const matchIndexRef = React.useRef<number | null>(null);

  useLayoutEffect(() => {
    if (open) {
      clearTimeout(timeoutIdRef.current);
      matchIndexRef.current = null;
      stringRef.current = '';
    }
  }, [open]);

  useLayoutEffect(() => {
    // Sync arrow key navigation but not typeahead navigation
    if (open && stringRef.current === '') {
      prevIndexRef.current = selectedIndex ?? activeIndex ?? -1;
    }
  }, [open, selectedIndex, activeIndex]);

  function onKeyDown(event: React.KeyboardEvent) {
    // Correctly scope non-portalled floating elements
    if (
      isElement(event.target) &&
      event.target.closest(
        '[role="dialog"],[role="menu"],[role="listbox"],[role="tree"],[role="grid"]'
      ) !== event.currentTarget
    ) {
      return;
    }

    if (stringRef.current.length > 0 && stringRef.current[0] !== ' ') {
      dataRef.current.typing = true;

      if (event.key === ' ') {
        stopEvent(event);
      }
    }

    const listContent = listRef.current;

    if (
      listContent == null ||
      ignoreKeys.includes(event.key) ||
      // Character key
      event.key.length !== 1 ||
      // Modifier key
      event.ctrlKey ||
      event.metaKey ||
      event.altKey
    ) {
      return;
    }

    // Bail out if the list contains a word like "llama" or "aaron". TODO:
    // allow it in this case, too.
    const allowRapidSuccessionOfFirstLetter = listContent.every((text) =>
      text
        ? text[0]?.toLocaleLowerCase() !== text[1]?.toLocaleLowerCase()
        : true
    );

    // Allows the user to cycle through items that start with the same letter
    // in rapid succession
    if (allowRapidSuccessionOfFirstLetter && stringRef.current === event.key) {
      stringRef.current = '';
      prevIndexRef.current = matchIndexRef.current;
    }

    stringRef.current += event.key;
    clearTimeout(timeoutIdRef.current);
    timeoutIdRef.current = setTimeout(() => {
      stringRef.current = '';
      prevIndexRef.current = matchIndexRef.current;
      dataRef.current.typing = false;
    }, resetMs);

    const prevIndex = prevIndexRef.current;

    const orderedList = [
      ...listContent.slice((prevIndex ?? 0) + 1),
      ...listContent.slice(0, (prevIndex ?? 0) + 1),
    ];

    const str = findMatch
      ? findMatch(orderedList, stringRef.current)
      : orderedList.find(
          (text) =>
            text
              ?.toLocaleLowerCase()
              .indexOf(stringRef.current.toLocaleLowerCase()) === 0
        );

    const index = str ? listContent.indexOf(str) : -1;

    if (index !== -1) {
      onMatch(index);
      matchIndexRef.current = index;
    }
  }

  if (!enabled) {
    return {};
  }

  return {
    reference: {onKeyDown},
    floating: {onKeyDown},
  };
};
