// packages/solid/src/components/FloatingFocusManager.tsx
import {isHTMLElement} from '@floating-ui/utils/dom';
import {
  activeElement,
  contains,
  getDocument,
  getTarget,
  isTypeableElement,
  stopEvent,
} from '@floating-ui/utils/react';
import {destructure} from '@solid-primitives/destructure';
import {
  createEffect,
  createMemo,
  JSX,
  mergeProps,
  onCleanup,
  ParentComponent,
  Show,
} from 'solid-js';
import {FocusableElement, tabbable} from 'tabbable';

import type {DismissPayload} from '../hooks/useDismiss';
import type {FloatingContext, ReferenceType} from '../types';
import {createAttribute} from '../utils/createAttribute';
import {enqueueFocus} from '../utils/enqueueFocus';
import {getAncestors} from '../utils/getAncestors';
import {getChildren} from '../utils/getChildren';
import {markOthers, supportsInert} from '../utils/markOthers';
import {
  getNextTabbable,
  getPreviousTabbable,
  getTabbableOptions,
  isOutsideEvent,
} from '../utils/tabbable';
import {usePortalContext} from './FloatingPortal';
import {useFloatingTree} from './FloatingTree';
import {FocusGuard, HIDDEN_STYLES} from './FocusGuard';

const VisuallyHiddenDismiss: ParentComponent<
  JSX.ButtonHTMLAttributes<HTMLButtonElement>
> = (props) => {
  return (
    <button {...props} type="button" tabIndex={-1} style={HIDDEN_STYLES} />
  );
};

export interface FloatingFocusManagerProps<
  RT extends ReferenceType = ReferenceType
> {
  context: FloatingContext<RT>;
  children: JSX.Element;
  disabled?: boolean;
  order?: Array<'reference' | 'floating' | 'content'>;
  initialFocus?: number | HTMLElement | null;
  guards?: boolean;
  returnFocus?: boolean;
  modal?: boolean;
  visuallyHiddenDismiss?: boolean | string;
  closeOnFocusOut?: boolean;
}

/**
 * Provides focus management for the floating element.
 * @see https://floating-ui.com/docs/FloatingFocusManager
 */
export function FloatingFocusManager<RT extends ReferenceType = ReferenceType>(
  props: FloatingFocusManagerProps<RT>
): JSX.Element {
  const mergedProps = mergeProps(
    {
      disabled: false,
      order: ['content'],
      guards: true,
      initialFocus: 0,
      returnFocus: true,
      modal: true,
      visuallyHiddenDismiss: false,
      closeOnFocusOut: true,
    } as Required<FloatingFocusManagerProps>,
    props
  );
  const {
    context,
    disabled,
    order,
    guards: _guards,
    initialFocus,
    returnFocus,
    modal,
    visuallyHiddenDismiss,
    closeOnFocusOut,
  } = destructure(mergedProps);
  const {open, refs, nodeId, onOpenChange, events, dataRef} = destructure(
    context()
  );

  // Force the guards to be rendered if the `inert` attribute is not supported.
  const guards = () => (supportsInert() ? _guards() : true);

  const tree = useFloatingTree();
  const portalContext = usePortalContext();

  // Controlled by `useListNavigation`.
  const ignoreInitialFocus =
    typeof initialFocus === 'number' && initialFocus < 0;

  let startDismissButtonRef: HTMLButtonElement | null = null;
  let endDismissButtonRef: HTMLButtonElement | null = null;
  let preventreturnFocus = false;
  let previouslyFocusedElementRef: Element | null = null;
  let isPointerDownRef = false;

  const isInsidePortal = portalContext != null;

  // If the reference is a combobox and is typeable (e.g. input/textarea),
  // there are different focus semantics. The guards should not be rendered, but
  // aria-hidden should be applied to all nodes still. Further, the visually
  // hidden dismiss button should only appear at the end of the list, not the
  // start.
  const isTypeableCombobox = createMemo(() => {
    const domReference = refs().reference() as HTMLElement | null;
    return (
      domReference &&
      domReference.getAttribute('role') === 'combobox' &&
      isTypeableElement(domReference)
    );
  });

  const getTabbableContent = (
    container: HTMLElement | null = refs().floating()
  ) => {
    return container ? tabbable(container, getTabbableOptions()) : [];
  };

  const getTabbableElements = (container?: HTMLElement) => {
    const content = getTabbableContent(container);
    const domReference = refs().reference() as HTMLElement | null;
    const floating = refs().floating() as HTMLElement | null;
    return order()
      ?.map((type: string) => {
        if (domReference && type === 'reference') {
          return domReference;
        }

        if (floating && type === 'floating') {
          return floating;
        }

        return content;
      })
      .filter(Boolean)
      .flat() as Array<FocusableElement>;
  };

  createEffect(() => {
    if (disabled() || !modal()) return;
    const domReference = refs().reference();
    const floating = refs().floating();

    function onKeyDown(event: KeyboardEvent) {
      if (event.key === 'Tab') {
        // The focus guards have nothing to focus, so we need to stop the event.
        if (
          contains(floating, activeElement(getDocument(floating))) &&
          getTabbableContent().length === 0 &&
          !isTypeableCombobox
        ) {
          stopEvent(event);
        }

        const els = getTabbableElements();
        const target = getTarget(event);

        if (order()[0] === 'reference' && target === domReference) {
          stopEvent(event);
          if (event.shiftKey) {
            enqueueFocus(els[els.length - 1]);
          } else {
            enqueueFocus(els[1]);
          }
        }

        if (
          order()[1] === 'floating' &&
          target === floating &&
          event.shiftKey
        ) {
          stopEvent(event);
          enqueueFocus(els[0]);
        }
      }
    }

    const doc = getDocument(floating);
    doc.addEventListener('keydown', onKeyDown);
    return () => {
      doc.removeEventListener('keydown', onKeyDown);
    };
  });

  createEffect(() => {
    if (disabled() || !closeOnFocusOut()) return;
    const domReference = refs().reference();
    const floating = refs().floating();
    // In Safari, buttons lose focus when pressing them.
    function handlePointerDown() {
      isPointerDownRef = true;
      setTimeout(() => {
        isPointerDownRef = false;
      });
    }

    function handleFocusOutside(event: FocusEvent) {
      const relatedTarget = event.relatedTarget as Element | null;

      queueMicrotask(() => {
        const movedToUnrelatedNode = !(
          contains(domReference as Element, relatedTarget) ||
          contains(floating, relatedTarget) ||
          contains(relatedTarget, floating) ||
          contains(portalContext?.portalNode(), relatedTarget) ||
          relatedTarget?.hasAttribute(createAttribute('focus-guard')) ||
          (tree() &&
            (getChildren(tree().nodesRef, nodeId()).find(
              (node) =>
                contains(node.context?.refs.floating(), relatedTarget) ||
                contains(
                  node.context?.refs.reference() as Element,
                  relatedTarget
                )
            ) ||
              getAncestors(tree().nodesRef, nodeId()).find(
                (node) =>
                  node.context?.refs.floating() === relatedTarget ||
                  node.context?.refs.reference() === relatedTarget
              )))
        );

        // Focus did not move inside the floating tree, and there are no tabbable
        // portal guards to handle closing.
        if (
          relatedTarget &&
          movedToUnrelatedNode &&
          !isPointerDownRef &&
          // Fix React 18 Strict Mode returnFocus due to double rendering.
          relatedTarget !== previouslyFocusedElementRef
        ) {
          preventreturnFocus = true;
          onOpenChange()(false, event);
        }
      });
    }

    if (floating && isHTMLElement(domReference)) {
      domReference.addEventListener('focusout', handleFocusOutside);
      domReference.addEventListener('pointerdown', handlePointerDown);
      !modal && floating.addEventListener('focusout', handleFocusOutside);

      onCleanup(() => {
        domReference.removeEventListener('focusout', handleFocusOutside);
        domReference.removeEventListener('pointerdown', handlePointerDown);
        !modal() &&
          floating.removeEventListener('focusout', handleFocusOutside);
      });
    }
  });

  createEffect(() => {
    if (disabled()) return;
    const domReference = refs().reference();
    const floating = refs().floating();
    // Don't hide portals nested within the parent portal.
    const portalNodes = Array.from(
      portalContext
        ?.portalNode()
        ?.querySelectorAll(`[${createAttribute('portal')}]`) || []
    );
    onCleanup(() => {
      if (floating) {
        const insideElements = [
          floating,
          ...portalNodes,
          startDismissButtonRef,
          endDismissButtonRef,
          order().includes('reference') || isTypeableCombobox()
            ? domReference
            : null,
        ].filter((x): x is Element => x != null);

        const cleanup = modal()
          ? markOthers(insideElements, guards(), !guards())
          : markOthers(insideElements);
        cleanup();
      }
    });
  });

  createEffect(() => {
    const floating = refs().floating();
    if (disabled() || !floating) return;

    const doc = getDocument(floating);
    const previouslyFocusedElement = activeElement(doc);

    // Wait for any layout effect state setters to execute to set `tabIndex`.
    queueMicrotask(() => {
      const focusableElements = getTabbableElements(floating);
      const initialFocusValue = initialFocus();

      const elToFocus =
        (typeof initialFocusValue === 'number'
          ? focusableElements[initialFocusValue]
          : initialFocusValue) || floating;
      const focusAlreadyInsideFloatingEl = contains(
        floating,
        previouslyFocusedElement
      );

      if (!ignoreInitialFocus && !focusAlreadyInsideFloatingEl && open()) {
        enqueueFocus(elToFocus, {preventScroll: elToFocus === floating});
      }
    });
  });

  createEffect(() => {
    const floating = refs().floating();
    if (disabled() || !floating) return;

    let preventReturnFocusScroll = false;

    const doc = getDocument(floating);
    const previouslyFocusedElement = activeElement(doc);
    const contextData = dataRef;

    previouslyFocusedElementRef = previouslyFocusedElement;

    // Dismissing via outside press should always ignore `returnFocus` to
    // prevent unwanted scrolling.
    function onDismiss(payload: DismissPayload) {
      if (payload.type === 'escapeKey' && refs().reference()) {
        previouslyFocusedElementRef = refs().reference() as Element | null;
      }

      if (['referencePress', 'escapeKey'].includes(payload.type)) {
        return;
      }

      const returnFocus = payload.data.returnFocus;

      if (typeof returnFocus === 'object') {
        preventreturnFocus = false;
        preventReturnFocusScroll = returnFocus.preventScroll;
      } else {
        preventreturnFocus = !returnFocus;
      }
    }

    events().on('dismiss', onDismiss);

    onCleanup(() => {
      events().off('dismiss', onDismiss);

      const activeEl = activeElement(doc);
      const openEvent = contextData().openEvent;
      const shouldFocusReference =
        contains(floating, activeEl) ||
        (tree &&
          getChildren(tree().nodesRef, nodeId()).some((node) =>
            contains(node.context?.refs.floating(), activeEl)
          )) ||
        (openEvent && ['click', 'mousedown'].includes(openEvent.type));

      if (shouldFocusReference && refs().reference()) {
        previouslyFocusedElementRef = refs().reference() as Element | null;
      }

      if (
        returnFocus() &&
        isHTMLElement(previouslyFocusedElementRef) &&
        !preventreturnFocus
      ) {
        enqueueFocus(previouslyFocusedElementRef, {
          // When dismissing nested floating elements, by the time the rAF has
          // executed, the menus will all have been unmounted. When they try
          // to get focused, the calls get ignored — leaving the root
          // reference focused as desired.
          cancelPrevious: false,
          preventScroll: preventReturnFocusScroll,
        });
      }
    });
  });

  // Synchronize the `context` & `modal` value to the FloatingPortal context.
  // It will decide whether or not it needs to render its own guards.
  createEffect(() => {
    if (disabled() || !portalContext) return;

    portalContext.setFocusManagerState({
      modal: modal(),
      closeOnFocusOut: closeOnFocusOut(),
      open: context().open(),
      onOpenChange,
      refs: refs(),
    });
  });
  onCleanup(() => {
    portalContext?.setFocusManagerState(null);
  });

  createEffect(() => {
    if (disabled()) return;
    const floating = refs().floating();

    if (floating && typeof MutationObserver === 'function') {
      const handleMutation = () => {
        const tabIndex = floating.getAttribute('tabindex');
        if (
          order().includes('floating') ||
          (activeElement(getDocument(floating)) !==
            (refs().reference() as Element) &&
            getTabbableContent().length === 0)
        ) {
          if (tabIndex !== '0') {
            floating.setAttribute('tabindex', '0');
          }
        } else if (tabIndex !== '-1') {
          floating.setAttribute('tabindex', '-1');
        }
      };

      handleMutation();
      const observer = new MutationObserver(handleMutation);

      observer.observe(floating, {
        childList: true,
        subtree: true,
        attributes: true,
      });

      onCleanup(() => {
        observer.disconnect();
      });
    }
  });

  function RenderDismissButton(props: {location: 'start' | 'end'}) {
    if (disabled() || !visuallyHiddenDismiss() || !modal()) {
      return null;
    }

    return (
      <VisuallyHiddenDismiss
        ref={(el) =>
          props.location === 'start'
            ? (startDismissButtonRef = el)
            : (endDismissButtonRef = el)
        }
        onClick={(event) => onOpenChange()(false, event)}
      >
        {typeof visuallyHiddenDismiss === 'string'
          ? visuallyHiddenDismiss
          : 'Dismiss'}
      </VisuallyHiddenDismiss>
    );
  }

  const shouldRenderGuards = createMemo(
    () =>
      !disabled() &&
      guards() &&
      !isTypeableCombobox &&
      (isInsidePortal || modal())
  );

  return (
    <>
      <Show when={shouldRenderGuards()}>
        <FocusGuard
          data-type="inside"
          ref={(el) => portalContext?.setRefs('beforeInsideRef', el)}
          onFocus={(event) => {
            if (modal()) {
              const els = getTabbableElements();
              enqueueFocus(
                order()[0] === 'reference' ? els[0] : els[els.length - 1]
              );
            } else if (
              portalContext?.preserveTabOrder &&
              portalContext.portalNode
            ) {
              preventreturnFocus = false;
              if (
                isOutsideEvent(
                  event,
                  portalContext.portalNode() as HTMLElement | undefined
                )
              ) {
                const nextTabbable = getNextTabbable() || refs().reference();
                nextTabbable?.focus();
              } else {
                portalContext.refs.beforeOutsideRef?.focus();
              }
            }
          }}
        />
      </Show>
      {/*
        Ensure the first swipe is the list item. The end of the listbox popup
        will have a dismiss button.
      */}
      <Show when={!isTypeableCombobox()}>
        <RenderDismissButton location="start" />
      </Show>

      {props.children}
      {<RenderDismissButton location="end" />}
      <Show when={shouldRenderGuards}>
        <FocusGuard
          data-type="inside"
          ref={(el) => portalContext?.setRefs('afterInsideRef', el)}
          onFocus={(event) => {
            if (modal()) {
              enqueueFocus(getTabbableElements()[0]);
            } else if (
              portalContext?.preserveTabOrder &&
              portalContext.portalNode()
            ) {
              if (closeOnFocusOut()) {
                preventreturnFocus = true;
              }

              if (
                isOutsideEvent(
                  event,
                  portalContext.portalNode() as Element | undefined
                )
              ) {
                const prevTabbable =
                  getPreviousTabbable() || refs().reference();
                prevTabbable?.focus();
              } else {
                portalContext.refs.afterOutsideRef?.focus();
              }
            }
          }}
        />
      </Show>
    </>
  );
}

// packages/react-dom-interactions/src/components/FloatingFocusManager.tsx
import {hideOthers} from 'aria-hidden';
import {FocusableElement, tabbable} from 'tabbable';
import * as React from 'react';
import useLayoutEffect from 'use-isomorphic-layout-effect';
import {usePortalContext} from './FloatingPortal';
import {useFloatingTree} from './FloatingTree';
import type {FloatingContext, ReferenceType} from '../types';
import {activeElement} from '../utils/activeElement';
import {FocusGuard, HIDDEN_STYLES} from './FocusGuard';
import {getDocument} from '../utils/getDocument';
import {getTarget} from '../utils/getTarget';
import {isHTMLElement} from '../utils/is';
import {isTypeableElement} from '../utils/isTypeableElement';
import {stopEvent} from '../utils/stopEvent';
import {useLatestRef} from '../hooks/utils/useLatestRef';
import {
  getNextTabbable,
  getPreviousTabbable,
  getTabbableOptions,
  isOutsideEvent,
} from '../utils/tabbable';
import {getChildren} from '../utils/getChildren';
import {getAncestors} from '../utils/getAncestors';
import {enqueueFocus} from '../utils/enqueueFocus';
import {contains} from '../utils/contains';
import {DismissPayload} from '../hooks/useDismiss';

const VisuallyHiddenDismiss = React.forwardRef(function VisuallyHiddenDismiss(
  props: React.ButtonHTMLAttributes<HTMLButtonElement>,
  ref: React.Ref<HTMLButtonElement>
) {
  return <button {...props} ref={ref} tabIndex={-1} style={HIDDEN_STYLES} />;
});

export interface Props<RT extends ReferenceType = ReferenceType> {
  context: FloatingContext<RT>;
  children: JSX.Element;
  order?: Array<'reference' | 'floating' | 'content'>;
  initialFocus?: number | React.MutableRefObject<HTMLElement | null>;
  guards?: boolean;
  returnFocus?: boolean;
  modal?: boolean;
  visuallyHiddenDismiss?: boolean | string;
  closeOnFocusOut?: boolean;
}

/**
 * Provides focus management for the floating element.
 * @see https://floating-ui.com/docs/FloatingFocusManager
 */
export function FloatingFocusManager<RT extends ReferenceType = ReferenceType>({
  context,
  children,
  order = ['content'],
  guards = true,
  initialFocus = 0,
  returnFocus = true,
  modal = true,
  visuallyHiddenDismiss = false,
  closeOnFocusOut = true,
}: Props<RT>): JSX.Element {
  const {
    refs,
    nodeId,
    onOpenChange,
    events,
    _: {domReference},
  } = context;

  const orderRef = useLatestRef(order);
  const tree = useFloatingTree();
  const portalContext = usePortalContext();
  const [tabbableContentLength, setTabbableContentLength] = React.useState<
    number | null
  >(null);

  // Controlled by `useListNavigation`.
  const initialFocusControlled =
    typeof initialFocus === 'number' && initialFocus < 0;

  const startDismissButtonRef = React.useRef<HTMLButtonElement>(null);
  const endDismissButtonRef = React.useRef<HTMLButtonElement>(null);
  const preventReturnFocusRef = React.useRef(false);
  const previouslyFocusedElementRef = React.useRef<Element | null>(null);
  const insidePortal = portalContext != null;

  // If the reference is a combobox and is typeable (e.g. input/textarea),
  // there are different focus semantics. The guards should not be rendered, but
  // aria-hidden should be applied to all nodes still. Further, the visually
  // hidden dismiss button should only appear at the end of the list, not the
  // start.
  const typeableCombobox =
    domReference &&
    domReference.getAttribute('role') === 'combobox' &&
    isTypeableElement(domReference);

  const getTabbableContent = React.useCallback(
    (container: HTMLElement | null = refs.floating.current) => {
      return container ? tabbable(container, getTabbableOptions()) : [];
    },
    [refs]
  );

  const getTabbableElements = React.useCallback(
    (container?: HTMLElement) => {
      const content = getTabbableContent(container);

      return orderRef.current
        .map((type) => {
          if (refs.domReference.current && type === 'reference') {
            return refs.domReference.current;
          }

          if (refs.floating.current && type === 'floating') {
            return refs.floating.current;
          }

          return content;
        })
        .filter(Boolean)
        .flat() as Array<FocusableElement>;
    },
    [orderRef, refs, getTabbableContent]
  );

  React.useEffect(() => {
    if (!modal) {
      return;
    }

    function onKeyDown(event: KeyboardEvent) {
      if (event.key === 'Tab') {
        // The focus guards have nothing to focus, so we need to stop the event.
        if (getTabbableContent().length === 0 && !typeableCombobox) {
          stopEvent(event);
        }

        const els = getTabbableElements();
        const target = getTarget(event);

        if (
          orderRef.current[0] === 'reference' &&
          target === refs.domReference.current
        ) {
          stopEvent(event);
          if (event.shiftKey) {
            enqueueFocus(els[els.length - 1]);
          } else {
            enqueueFocus(els[1]);
          }
        }

        if (
          orderRef.current[1] === 'floating' &&
          target === refs.floating.current &&
          event.shiftKey
        ) {
          stopEvent(event);
          enqueueFocus(els[0]);
        }
      }
    }

    const doc = getDocument(refs.floating.current);
    doc.addEventListener('keydown', onKeyDown);
    return () => {
      doc.removeEventListener('keydown', onKeyDown);
    };
  }, [
    modal,
    orderRef,
    refs,
    typeableCombobox,
    getTabbableContent,
    getTabbableElements,
  ]);

  React.useEffect(() => {
    if (!closeOnFocusOut) {
      return;
    }
    const floating = refs.floating.current;
    const reference = refs.domReference.current;

    let isPointerDown = false;

    // In Safari, buttons lose focus when pressing them.
    function handlePointerDown() {
      isPointerDown = true;
      setTimeout(() => {
        isPointerDown = false;
      });
    }

    function handleFocusOutside(event: FocusEvent) {
      const relatedTarget = event.relatedTarget as Element | null;

      const movedToUnrelatedNode = !(
        contains(reference, relatedTarget) ||
        contains(floating, relatedTarget) ||
        contains(relatedTarget, floating) ||
        contains(portalContext?.portalNode, relatedTarget) ||
        [
          portalContext?.beforeOutsideRef.current,
          portalContext?.afterOutsideRef.current,
        ]
          .filter(Boolean)
          .includes(relatedTarget as HTMLSpanElement | null) ||
        (tree &&
          (getChildren(tree.nodesRef.current, nodeId).find(
            (node) =>
              contains(node.context?.refs.floating.current, relatedTarget) ||
              contains(node.context?.refs.domReference.current, relatedTarget)
          ) ||
            getAncestors(tree.nodesRef.current, nodeId).find(
              (node) =>
                node.context?.refs.floating.current === relatedTarget ||
                node.context?.refs.domReference.current === relatedTarget
            )))
      );

      // Focus did not move inside the floating tree, and there are no tabbable
      // portal guards to handle closing.
      if (
        relatedTarget &&
        movedToUnrelatedNode &&
        !isPointerDown &&
        // Fix React 18 Strict Mode returnFocus due to double rendering.
        relatedTarget !== previouslyFocusedElementRef.current
      ) {
        preventReturnFocusRef.current = true;
        // On iOS VoiceOver, dismissing the nested submenu will cause the
        // first item of the list to receive focus. Delaying it appears to fix
        // the issue.
        setTimeout(() => onOpenChange(false));
      }
    }

    if (floating && isHTMLElement(reference)) {
      reference.addEventListener('focusout', handleFocusOutside);
      reference.addEventListener('pointerdown', handlePointerDown);
      !modal && floating.addEventListener('focusout', handleFocusOutside);

      return () => {
        reference.removeEventListener('focusout', handleFocusOutside);
        reference.removeEventListener('pointerdown', handlePointerDown);
        !modal && floating.removeEventListener('focusout', handleFocusOutside);
      };
    }
  }, [modal, nodeId, tree, refs, portalContext, onOpenChange, closeOnFocusOut]);

  React.useEffect(() => {
    const floating = refs.floating.current;
    const reference = refs.domReference.current;
    // Don't hide portals nested within the parent portal.
    const portalNodes = Array.from(
      portalContext?.portalNode?.querySelectorAll(
        '[data-floating-ui-portal]'
      ) ?? []
    );

    function getDismissButtons() {
      return [
        startDismissButtonRef.current,
        endDismissButtonRef.current,
      ].filter(Boolean) as Array<Element>;
    }

    if (floating && isHTMLElement(reference) && modal) {
      const insideNodes = [floating, ...portalNodes, ...getDismissButtons()];
      const cleanup = hideOthers(
        orderRef.current.includes('reference') || typeableCombobox
          ? insideNodes.concat(reference)
          : insideNodes
      );

      return () => {
        cleanup();
      };
    }
  }, [modal, orderRef, portalContext, refs, typeableCombobox]);

  React.useEffect(() => {
    const floating = refs.floating.current;

    if (modal && !guards && floating) {
      const tabIndexValues: Array<string | null> = [];
      const options = getTabbableOptions();
      const allTabbable = tabbable(getDocument(floating).body, options);
      const floatingTabbable = getTabbableElements();

      // Exclude all tabbable elements that are part of the order
      const elements = allTabbable.filter(
        (el) => !floatingTabbable.includes(el)
      );

      elements.forEach((el, i) => {
        tabIndexValues[i] = el.getAttribute('tabindex');
        el.setAttribute('tabindex', '-1');
      });

      return () => {
        elements.forEach((el, i) => {
          const value = tabIndexValues[i];
          if (value == null) {
            el.removeAttribute('tabindex');
          } else {
            el.setAttribute('tabindex', value);
          }
        });
      };
    }
  }, [modal, guards, refs, getTabbableElements]);

  // Layout effect to ensure that the previouslyFocusedElement is set before
  // focus is moved inside the floating element via hooks like
  // useListNavigation.
  useLayoutEffect(() => {
    const floating = refs.floating.current;
    if (!floating) {
      return;
    }

    const doc = getDocument(floating);

    let returnFocusValue = returnFocus;
    let preventReturnFocusScroll = false;
    const previouslyFocusedElement = activeElement(doc);

    previouslyFocusedElementRef.current = previouslyFocusedElement;

    const focusableElements = getTabbableElements(floating);
    const elToFocus =
      (typeof initialFocus === 'number'
        ? focusableElements[initialFocus]
        : initialFocus.current) || floating;

    // If the `useListNavigation` hook is active, always ignore `initialFocus`
    // because it has its own handling of the initial focus.
    !initialFocusControlled &&
      enqueueFocus(elToFocus, {preventScroll: elToFocus === floating});

    // Dismissing via outside press should always ignore `returnFocus` to
    // prevent unwanted scrolling.
    function onDismiss(payload: DismissPayload) {
      if (payload.type === 'escapeKey' && refs.domReference.current) {
        previouslyFocusedElementRef.current = refs.domReference.current;
      }

      if (payload.type !== 'outsidePress') {
        return;
      }

      const returnFocus = payload.data.returnFocus;

      if (typeof returnFocus === 'object') {
        returnFocusValue = true;
        preventReturnFocusScroll = returnFocus.preventScroll;
      } else {
        returnFocusValue = returnFocus;
      }
    }

    events.on('dismiss', onDismiss);

    return () => {
      events.off('dismiss', onDismiss);

      if (contains(floating, activeElement(doc)) && refs.domReference.current) {
        previouslyFocusedElementRef.current = refs.domReference.current;
      }

      if (
        returnFocusValue &&
        isHTMLElement(previouslyFocusedElementRef.current) &&
        !preventReturnFocusRef.current
      ) {
        enqueueFocus(previouslyFocusedElementRef.current, {
          preventScroll: preventReturnFocusScroll,
          // When dismissing nested floating elements, by the time the rAF has
          // executed, the menus will all have been unmounted. When they try
          // to get focused, the calls get ignored — leaving the root reference
          // focused as desired.
          cancelPrevious: false,
        });
      }
    };
  }, [
    getTabbableElements,
    initialFocus,
    returnFocus,
    refs,
    events,
    initialFocusControlled,
  ]);

  // Synchronize the `context` & `modal` value to the FloatingPortal context.
  // It will decide whether or not it needs to render its own guards.
  useLayoutEffect(() => {
    if (!portalContext) return;
    portalContext.setFocusManagerState({
      ...context,
      modal,
      // Not concerned about the <RT> generic type.
    } as any);
    return () => {
      portalContext.setFocusManagerState(null);
    };
  }, [portalContext, modal, context]);

  useLayoutEffect(() => {
    if (getTabbableContent().length === 0 && !initialFocusControlled) {
      setTabbableContentLength(0);
    }
  }, [getTabbableContent, refs, initialFocusControlled]);

  const shouldRenderGuards =
    guards && (insidePortal || modal) && !typeableCombobox;

  function renderDismissButton(location: 'start' | 'end') {
    return visuallyHiddenDismiss && modal ? (
      <VisuallyHiddenDismiss
        ref={location === 'start' ? startDismissButtonRef : endDismissButtonRef}
        onClick={() => onOpenChange(false)}
      >
        {typeof visuallyHiddenDismiss === 'string'
          ? visuallyHiddenDismiss
          : 'Dismiss'}
      </VisuallyHiddenDismiss>
    ) : null;
  }

  return (
    <>
      {shouldRenderGuards && (
        <FocusGuard
          ref={portalContext?.beforeInsideRef}
          onFocus={(event) => {
            if (modal) {
              const els = getTabbableElements();
              enqueueFocus(
                order[0] === 'reference' ? els[0] : els[els.length - 1]
              );
            } else if (
              portalContext?.preserveTabOrder &&
              portalContext.portalNode
            ) {
              preventReturnFocusRef.current = false;
              if (isOutsideEvent(event, portalContext.portalNode)) {
                const nextTabbable = getNextTabbable() || domReference;
                nextTabbable?.focus();
              } else {
                portalContext.beforeOutsideRef.current?.focus();
              }
            }
          }}
        />
      )}
      {/*
        Ensure the first swipe is the list item. The end of the listbox popup
        will have a dismiss button.
      */}
      {typeableCombobox ? null : renderDismissButton('start')}
      {React.cloneElement(
        children,
        tabbableContentLength === 0 || order.includes('floating')
          ? {tabIndex: 0}
          : {}
      )}
      {renderDismissButton('end')}
      {shouldRenderGuards && (
        <FocusGuard
          ref={portalContext?.afterInsideRef}
          onFocus={(event) => {
            if (modal) {
              enqueueFocus(getTabbableElements()[0]);
            } else if (
              portalContext?.preserveTabOrder &&
              portalContext.portalNode
            ) {
              preventReturnFocusRef.current = true;
              if (isOutsideEvent(event, portalContext.portalNode)) {
                const prevTabbable = getPreviousTabbable() || domReference;
                prevTabbable?.focus();
              } else {
                portalContext.afterOutsideRef.current?.focus();
              }
            }
          }}
        />
      )}
    </>
  );
}
