// packages/solid/src/hooks/useRole.ts
import {Accessor, createUniqueId, mergeProps} from 'solid-js';

import type {ElementProps, FloatingContext, ReferenceType} from '../types';

export interface UseRoleProps {
  enabled?: Accessor<boolean>;

  role?:
    | 'tooltip'
    | 'dialog'
    | 'alertdialog'
    | 'menu'
    | 'listbox'
    | 'grid'
    | 'tree';
}

/**
 * Adds base screen reader props to the reference and floating elements for a
 * given floating element `role`.
 * @see https://floating-ui.com/docs/useRole
 */
export function useRole<RT extends ReferenceType = ReferenceType>(
  context: FloatingContext<RT>,
  props: UseRoleProps = {}
): ElementProps {
  const mergedProps = mergeProps(
    {
      enabled: () => true,
      role: 'dialog',
    } as Required<UseRoleProps>,
    props
  );

  const referenceId = createUniqueId();

  const floatingProps = {id: context.floatingId, role: mergedProps.role};

  if (mergedProps.role === 'tooltip') {
    return {
      reference: {
        'aria-describedby': context.open() ? context.floatingId : undefined,
      },
      floating: floatingProps,
    };
  }
  return !mergedProps.enabled()
    ? {}
    : {
        reference: {
          'aria-expanded': context.open() ? 'true' : 'false',
          'aria-haspopup':
            mergedProps.role === 'alertdialog' ? 'dialog' : mergedProps.role,
          'aria-controls': context.open() ? context.floatingId : undefined,
          ...(mergedProps.role === 'listbox' && {
            role: 'combobox',
          }),
          ...(mergedProps.role === 'menu' && {
            id: referenceId,
          }),
        },
        floating: {
          ...floatingProps,
          ...(mergedProps.role === 'menu' && {
            'aria-labelledby': referenceId,
          }),
        },
      };
}

// packages/react/src/hooks/useRole.ts
import * as React from 'react';

import type {ElementProps, FloatingContext, ReferenceType} from '../types';
import {useId} from './useId';

export interface Props {
  enabled?: boolean;
  role?:
    | 'tooltip'
    | 'dialog'
    | 'alertdialog'
    | 'menu'
    | 'listbox'
    | 'grid'
    | 'tree';
}

/**
 * Adds base screen reader props to the reference and floating elements for a
 * given floating element `role`.
 * @see https://floating-ui.com/docs/useRole
 */
export const useRole = <RT extends ReferenceType = ReferenceType>(
  context: FloatingContext<RT>,
  props: Partial<Props> = {}
): ElementProps => {
  const {open, floatingId} = context;
  const {enabled = true, role = 'dialog'} = props;

  const referenceId = useId();

  return React.useMemo(() => {
    const floatingProps = {id: floatingId, role};

    if (!enabled) {
      return {};
    }

    if (role === 'tooltip') {
      return {
        reference: {
          'aria-describedby': open ? floatingId : undefined,
        },
        floating: floatingProps,
      };
    }

    return {
      reference: {
        'aria-expanded': open ? 'true' : 'false',
        'aria-haspopup': role === 'alertdialog' ? 'dialog' : role,
        'aria-controls': open ? floatingId : undefined,
        ...(role === 'listbox' && {
          role: 'combobox',
        }),
        ...(role === 'menu' && {
          id: referenceId,
        }),
      },
      floating: {
        ...floatingProps,
        ...(role === 'menu' && {
          'aria-labelledby': referenceId,
        }),
      },
    };
  }, [enabled, role, open, floatingId, referenceId]);
};
